# Generated by Django 4.2.6 on 2023-12-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='other',
        ),
    ]
