# Generated by Django 4.2.6 on 2023-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
